// Ported verbatim from oxc_linter::globals::VALID_ARIA_ROLES.
// Source: https://www.w3.org/TR/wai-aria/#role_definitions and the
// aria-query npm package (rolesMap).

export const VALID_ARIA_ROLES: ReadonlySet<string> = new Set([
  "alert",
  "alertdialog",
  "application",
  "article",
  "banner",
  "blockquote",
  "button",
  "caption",
  "cell",
  "checkbox",
  "code",
  "columnheader",
  "combobox",
  "complementary",
  "contentinfo",
  "definition",
  "deletion",
  "dialog",
  "directory",
  "doc-abstract",
  "doc-acknowledgments",
  "doc-afterword",
  "doc-appendix",
  "doc-backlink",
  "doc-biblioentry",
  "doc-bibliography",
  "doc-biblioref",
  "doc-chapter",
  "doc-colophon",
  "doc-conclusion",
  "doc-cover",
  "doc-credit",
  "doc-credits",
  "doc-dedication",
  "doc-endnote",
  "doc-endnotes",
  "doc-epigraph",
  "doc-epilogue",
  "doc-errata",
  "doc-example",
  "doc-footnote",
  "doc-foreword",
  "doc-glossary",
  "doc-glossref",
  "doc-index",
  "doc-introduction",
  "doc-noteref",
  "doc-notice",
  "doc-pagebreak",
  "doc-pagelist",
  "doc-part",
  "doc-preface",
  "doc-prologue",
  "doc-pullquote",
  "doc-qna",
  "doc-subtitle",
  "doc-tip",
  "doc-toc",
  "document",
  "emphasis",
  "feed",
  "figure",
  "form",
  "generic",
  "graphics-document",
  "graphics-object",
  "graphics-symbol",
  "grid",
  "gridcell",
  "group",
  "heading",
  "img",
  "insertion",
  "link",
  "list",
  "listbox",
  "listitem",
  "log",
  "main",
  "mark",
  "marquee",
  "math",
  "menu",
  "menubar",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "meter",
  "navigation",
  "none",
  "note",
  "option",
  "paragraph",
  "presentation",
  "progressbar",
  "radio",
  "radiogroup",
  "region",
  "row",
  "rowgroup",
  "rowheader",
  "scrollbar",
  "search",
  "searchbox",
  "separator",
  "slider",
  "spinbutton",
  "status",
  "strong",
  "subscript",
  "superscript",
  "switch",
  "tab",
  "table",
  "tablist",
  "tabpanel",
  "term",
  "textbox",
  "time",
  "timer",
  "toolbar",
  "tooltip",
  "tree",
  "treegrid",
  "treeitem",
]);

// Roles that imply user interaction. Mirrors `INTERACTIVE_ROLES` in
// oxc's react util.
export const INTERACTIVE_ROLES: ReadonlySet<string> = new Set([
  "button",
  "checkbox",
  "columnheader",
  "combobox",
  "grid",
  "gridcell",
  "link",
  "listbox",
  "menu",
  "menubar",
  "menuitem",
  "menuitemcheckbox",
  "menuitemradio",
  "option",
  "radio",
  "radiogroup",
  "row",
  "rowheader",
  "scrollbar",
  "searchbox",
  "separator",
  "slider",
  "spinbutton",
  "switch",
  "tab",
  "tablist",
  "textbox",
  // toolbar isn't strictly a widget but supports aria-activedescendant
  // — treated as a widget in practice.
  "toolbar",
  "tree",
  "treegrid",
  "treeitem",
]);

// Roles whose semantics are non-interactive content. Mirrors
// `NON_INTERACTIVE_ROLES`.
export const NON_INTERACTIVE_ROLES: ReadonlySet<string> = new Set([
  "alert",
  "alertdialog",
  "application",
  "article",
  "banner",
  "blockquote",
  "caption",
  "cell",
  "complementary",
  "contentinfo",
  "definition",
  "deletion",
  "dialog",
  "directory",
  "document",
  "feed",
  "figure",
  "form",
  "group",
  "heading",
  "img",
  "insertion",
  "list",
  "listitem",
  "log",
  "main",
  "marquee",
  "math",
  "navigation",
  "note",
  "paragraph",
  // progressbar is technically widget-derived but its value is
  // always read-only — treated as non-interactive in practice.
  "progressbar",
  "region",
  // `row` lives in INTERACTIVE_ROLES above (it's user-navigable inside
  // a grid / treegrid). Upstream `eslint-plugin-jsx-a11y` classifies
  // `rowgroup` (a passive container of rows) as non-interactive, but
  // not `row` itself.
  "rowgroup",
  "search",
  "status",
  "table",
  "tabpanel",
  "term",
  "time",
  "timer",
  "tooltip",
]);

// Abstract WAI-ARIA roles — never used as an actual role attribute,
// only for inheritance documentation.
export const ABSTRACT_ROLES: ReadonlySet<string> = new Set([
  "command",
  "composite",
  "input",
  "landmark",
  "range",
  "roletype",
  "section",
  "sectionhead",
  "select",
  "structure",
  "widget",
  "window",
]);

// `role="presentation"` and `role="none"` indicate the element should
// be ignored by assistive technology.
export const PRESENTATION_ROLES: ReadonlySet<string> = new Set(["presentation", "none"]);
